import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const Pretendard = localFont({
  src: [
    {
      path: "fonts/Pretendard-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/Pretendard-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "fonts/Pretendard-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "fonts/Pretendard-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Pretendard.className}`}>
        <main className="grid grid-rows-[20px_1fr_20px] min-h-screen p-4 pb-20 sm:p-20 ">
          {children}
        </main>
      </body>
    </html>
  );
}
